#!/usr/bin/env bash
# A script that transfers a file from our client to a server:

if [ $# -lt 3  ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit;
fi;
# Named parameters
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

if [ $# -ge 4 ];then
scp -o StrictHostKeyChecking=no -i "PATH_TO_SSH_KEY" "PATH_TO_FILE" "USERNAME"@"IP":~/  
else
scp -o StrictHostKeyChecking=no "PATH_TO_FILE" "USERNAME"@"IP":~/ 
fi;
