#!/usr/bin/env bash
# Install nginx web server and configure it to learn on port 80
# print "Hello world"

sudo apt-get update 
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx start